# automatically generated by the FlatBuffers compiler, do not modify

# namespace: response_proto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Response_Message(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response_Message()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse_Message(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response_Message
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response_Message
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Response_Message
    def Code(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Response_Message
    def Contents(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Response_MessageStart(builder): builder.StartObject(3)
def Start(builder):
    return Response_MessageStart(builder)
def Response_MessageAddType(builder, type): builder.PrependInt32Slot(0, type, 0)
def AddType(builder, type):
    return Response_MessageAddType(builder, type)
def Response_MessageAddCode(builder, code): builder.PrependInt32Slot(1, code, 0)
def AddCode(builder, code):
    return Response_MessageAddCode(builder, code)
def Response_MessageAddContents(builder, contents): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(contents), 0)
def AddContents(builder, contents):
    return Response_MessageAddContents(builder, contents)
def Response_MessageEnd(builder): return builder.EndObject()
def End(builder):
    return Response_MessageEnd(builder)