# automatically generated by the FlatBuffers compiler, do not modify

# namespace: grocery_proto

class BreadType(object):
    whole_wheat = 0
    white = 1
    pumpernickel = 2
    rye = 3
    sourdough = 4
