# automatically generated by the FlatBuffers compiler, do not modify

# namespace: grocery_proto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Cans(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # Cans
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Cans
    def Coke(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Cans
    def Beer(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Cans
    def Rootbeer(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateCans(builder, coke, beer, rootbeer):
    builder.Prep(4, 12)
    builder.PrependInt32(rootbeer)
    builder.PrependInt32(beer)
    builder.PrependInt32(coke)
    return builder.Offset()
