# automatically generated by the FlatBuffers compiler, do not modify

# namespace: grocery_proto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Drinks(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # Drinks
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Drinks
    def Cans(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # Drinks
    def Bottles(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj


def CreateDrinks(builder, cans_coke, cans_beer, cans_rootbeer, bottles_sprite, bottles_gingerale, bottles_lemonade):
    builder.Prep(4, 24)
    builder.Prep(4, 12)
    builder.PrependInt32(bottles_lemonade)
    builder.PrependInt32(bottles_gingerale)
    builder.PrependInt32(bottles_sprite)
    builder.Prep(4, 12)
    builder.PrependInt32(cans_rootbeer)
    builder.PrependInt32(cans_beer)
    builder.PrependInt32(cans_coke)
    return builder.Offset()
