# automatically generated by the FlatBuffers compiler, do not modify

# namespace: health_proto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Contents(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 28

    # Contents
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Contents
    def Dispenser(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Contents
    def Icemaker(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Contents
    def Lightbulb(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Contents
    def FridgeTemp(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # Contents
    def FreezerTemp(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # Contents
    def SensorStatus(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))
    # Contents
    def CapacityFull(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))

def CreateContents(builder, dispenser, icemaker, lightbulb, fridgeTemp, freezerTemp, sensorStatus, capacityFull):
    builder.Prep(4, 28)
    builder.PrependInt32(capacityFull)
    builder.PrependInt32(sensorStatus)
    builder.PrependInt32(freezerTemp)
    builder.PrependInt32(fridgeTemp)
    builder.PrependInt32(lightbulb)
    builder.PrependInt32(icemaker)
    builder.PrependInt32(dispenser)
    return builder.Offset()
