# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto2

class MilkType(object):
    one_percent = 0
    two_percent = 1
    fat_free = 2
    whole = 3
    almond = 4
    cashew = 5
    oat = 6
